"""add pmwb_active_optimization table

Revision ID: 1a2df557c710
Revises: 20260821000002
Create Date: 2026-08-23 20:54:04.518813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '1a2df557c710'
down_revision: Union[str, None] = '20260821000002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pmwb_active_optimization',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='自增ID'),
        sa.Column('title', sa.String(length=256), nullable=False, comment='工单标题'),
        sa.Column('current_situation', sa.Text(), nullable=True, comment='现状描述'),
        sa.Column('suggestion', sa.Text(), nullable=True, comment='优化建议'),
        sa.Column('admin_name', sa.String(length=64), nullable=True, comment='业务管理员'),
        sa.Column('status', sa.Enum('pending', 'adopted', 'rejected'), nullable=True, comment='评估状态：pending(待评估)/adopted(已采纳)/rejected(不采纳)'),
        sa.Column('req_id', sa.String(length=64), nullable=True, comment='关联需求文号'),
        sa.Column('note', sa.Text(), nullable=True, comment='备注说明'),
        sa.Column('created_by', sa.String(length=64), nullable=True, comment='创建人'),
        sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
        sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
        sa.PrimaryKeyConstraint('id'),
        comment='主动优化建议工单表'
    )
    op.create_index('idx_active_opt_admin_name', 'pmwb_active_optimization', ['admin_name'], unique=False)
    op.create_index('idx_active_opt_req_id', 'pmwb_active_optimization', ['req_id'], unique=False)
    op.create_index('idx_active_opt_status', 'pmwb_active_optimization', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_active_opt_status', table_name='pmwb_active_optimization')
    op.drop_index('idx_active_opt_req_id', table_name='pmwb_active_optimization')
    op.drop_index('idx_active_opt_admin_name', table_name='pmwb_active_optimization')
    op.drop_table('pmwb_active_optimization')
    # ### end Alembic commands ###
