"""add pmwb_research_issue table

Revision ID: bf9d37f54af3
Revises: 20260829000001
Create Date: 2026-08-29 18:16:05.498599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'bf9d37f54af3'
down_revision: Union[str, None] = '20260829000001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pmwb_research_issue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='自增ID'),
    sa.Column('issue_no', sa.String(length=64), nullable=False, comment='调研工单编号'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='工单标题'),
    sa.Column('sub_type', sa.Enum('leader_research', 'frontline_station'), nullable=True, comment='子类：领导调研/一线驻点'),
    sa.Column('status', sa.Enum('pending', 'processing', 'verify', 'resolved', 'closed', 'suspended'), nullable=True, comment='状态：待处理/处理中/验证中/已解决/已关闭/已挂起'),
    sa.Column('city', sa.String(length=64), nullable=True, comment='地市'),
    sa.Column('basic_info', sa.Text(), nullable=True, comment='基本信息'),
    sa.Column('situation_desc', sa.Text(), nullable=True, comment='情况说明'),
    sa.Column('city_suggestion', sa.Text(), nullable=True, comment='地市建议'),
    sa.Column('feedback_name', sa.String(length=128), nullable=True, comment='反馈人姓名'),
    sa.Column('feedback_phone', sa.String(length=64), nullable=True, comment='联系电话'),
    sa.Column('case_info', sa.Text(), nullable=True, comment='案例信息'),
    sa.Column('source', sa.String(length=128), nullable=True, comment='信息来源'),
    sa.Column('feedback_deadline', sa.Date(), nullable=True, comment='反馈截止日期'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('vendor_handlers', sa.String(length=512), nullable=True, comment='厂家责任人（多选，逗号分隔）'),
    sa.Column('assessment_result', sa.Text(), nullable=True, comment='评估结果'),
    sa.Column('issue_nature', sa.Enum('bug', 'optimization', 'invalid'), nullable=True, comment='问题性质：BUG/优化/非有效问题'),
    sa.Column('solution', sa.Text(), nullable=True, comment='解决方案'),
    sa.Column('business_admin', sa.String(length=512), nullable=True, comment='业务管理员（多选，逗号分隔）'),
    sa.Column('related_req_id', sa.String(length=64), nullable=True, comment='关联需求编号'),
    sa.Column('related_issue_id', sa.Integer(), nullable=True, comment='关联运营/调研工单ID'),
    sa.Column('related_meeting_id', sa.Integer(), nullable=True, comment='关联会议ID'),
    sa.Column('version_plan', sa.String(length=128), nullable=True, comment='版本计划'),
    sa.Column('official_feedback', sa.Text(), nullable=True, comment='正式反馈信息'),
    sa.Column('domain_code', sa.String(length=64), nullable=True, comment='关联业务领域编码'),
    sa.Column('impact_level', sa.Enum('P0', 'P1', 'P2', 'P3'), nullable=True, comment='影响等级'),
    sa.Column('go_live_date', sa.Date(), nullable=True, comment='计划完成时间'),
    sa.Column('resolve_date', sa.DateTime(), nullable=True, comment='解决时间'),
    sa.Column('is_overdue', sa.Integer(), nullable=True, comment='是否超期'),
    sa.Column('obsidian_path', sa.String(length=512), nullable=True, comment='沉淀知识条目路径'),
    sa.Column('attachments', sa.Text(), nullable=True, comment='附件元信息(JSON 数组)'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('issue_no'),
    comment='一线调研工单表'
    )
    op.create_index('idx_research_city', 'pmwb_research_issue', ['city'], unique=False)
    op.create_index('idx_research_issue_nature', 'pmwb_research_issue', ['issue_nature'], unique=False)
    op.create_index('idx_research_issue_no', 'pmwb_research_issue', ['issue_no'], unique=False)
    op.create_index('idx_research_related_issue', 'pmwb_research_issue', ['related_issue_id'], unique=False)
    op.create_index('idx_research_related_meeting', 'pmwb_research_issue', ['related_meeting_id'], unique=False)
    op.create_index('idx_research_related_req', 'pmwb_research_issue', ['related_req_id'], unique=False)
    op.create_index('idx_research_status', 'pmwb_research_issue', ['status'], unique=False)
    op.create_index('idx_research_sub_type', 'pmwb_research_issue', ['sub_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_research_sub_type', table_name='pmwb_research_issue')
    op.drop_index('idx_research_status', table_name='pmwb_research_issue')
    op.drop_index('idx_research_related_req', table_name='pmwb_research_issue')
    op.drop_index('idx_research_related_meeting', table_name='pmwb_research_issue')
    op.drop_index('idx_research_related_issue', table_name='pmwb_research_issue')
    op.drop_index('idx_research_issue_no', table_name='pmwb_research_issue')
    op.drop_index('idx_research_issue_nature', table_name='pmwb_research_issue')
    op.drop_index('idx_research_city', table_name='pmwb_research_issue')
    op.drop_table('pmwb_research_issue')
    # ### end Alembic commands ###
